apiVersion: apps/v1
kind: Deployment
metadata:
  name: praveenbus-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: praveenbus-backend
  template:
    metadata:
      labels:
        app: praveenbus-backend
    spec:
      containers:
        - name: praveenbus-backend
          image: naidu289/praveenbus-backend:latest
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: "your-database-host"
            - name: DB_USER
              value: "your-database-user"
            - name: DB_PASSWORD
              value: "your-database-password"

---
apiVersion: v1
kind: Service
metadata:
  name: praveenbus-service
spec:
  selector:
    app: praveenbus-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
