name: Deploy PraveenBus to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/praveenbus
            git pull origin main
            cd backend
            npm install
            pm2 restart praveenbus-backend || pm2 start server.js --name praveenbus-backend
            cd ../frontend
            npm install
            pm2 restart praveenbus-frontend || pm2 start npm --name praveenbus-frontend -- start
          EOF
